name: Release npm package

on:
  push:
    branches:
      - master
      - next-3

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: "22"
      - name: npm install and build
        run:
          npm ci
          npm run build:production
      - name: Build docker image
        run: docker build -t exist-db -f Dockerfile .
      - name: Start docker image
        run: docker run --publish 8080:8080 --detach exist-db
      - name: Wait for eXist
        uses: iFaxity/wait-on-action@v1
        with:
          resource: http-get://localhost:8080/exist/apps/tei-publisher/api/version
      - run: npm test
      - run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
